### ISSUE TITLE
Vulkan does not work on NVidia

### ISSUE THREAD

**Issue by paroj** [libretro/retroarch-snap#50]
It needs something along the lines of:
```yml
apps:
  retroarch:
    environment:
      VK_ICD_FILENAMES: /var/lib/snapd/lib/vulkan/icd.d/nvidia_icd.json
```

see https://forum.snapcraft.io/t/correct-way-to-do-nvidia-vulkan/20361/2 for how to implement this without breaking non-nvidia platforms.

relates to #45
